sudo: false

language: node_js

node_js:
  - "0.12"
  - "iojs"

notifications:
  slack: norch:wLsHiXjnAH5BdtTq3qtAqGp7

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install: 
  - export JOBS=max
  - export prebuild_compile=true

install:
  - npm install

script:
  - npm test
